#!/bin/bash

#simple update & upgrade with switch yes being activat bash script
#echo "Updating will begin after you input the sudoers password"
sudo apt update && sudo apt upgrade -y
#echo "Updating was successful"




